#!/usr/bin/env python3
"""Drive the recompiler's explicit-function-span mechanism to a fixed point.

Each round: census the orphaned branch targets left as "// ERROR <addr>" stubs,
derive a span for the parent function of each, re-run the tool, repeat. Stops
when the stub count reaches zero or stops improving.
"""
import bisect
import collections
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
TOOL = os.path.join(ROOT, ".research", "XenonRecomp", "build-clang",
                    "XenonRecomp", "XenonRecomp.exe")
HEADER = os.path.join(ROOT, "src", "ppc_context.h")
BASE_CONFIG = os.path.join(ROOT, "mcla_jts_regen.toml")
WORK_CONFIG = os.path.join(ROOT, "mcla_iter_regen.toml")
OUTDIR = os.path.join(ROOT, "build", "xr_iter")

STUB = re.compile(r"//\s*ERROR:?\s*(?:0x)?([0-9A-Fa-f]{8})")
MAPENT = re.compile(r"\s*\{ (0x[0-9A-Fa-f]+), sub_")
MAX_ROUNDS = 8


def read(p):
    with open(p, encoding="utf8", errors="ignore") as f:
        return f.read()


def mapping_addrs(d):
    out = set()
    for line in read(os.path.join(d, "ppc_func_mapping.cpp")).splitlines():
        m = MAPENT.match(line)
        if m:
            out.add(int(m.group(1), 16))
    return sorted(out)


def census(d):
    c = collections.Counter()
    for name in os.listdir(d):
        if name.startswith("ppc_recomp.") and name.endswith(".cpp"):
            for m in STUB.finditer(read(os.path.join(d, name))):
                c[int(m.group(1), 16)] += 1
    return c


def derive_spans(targets, mps):
    """parent = nearest mapping entry at or below; size runs to the next entry
    above the highest orphan belonging to that parent."""
    by = collections.defaultdict(list)
    for t in targets:
        j = bisect.bisect_left(mps, t)
        if j == 0:
            continue
        by[mps[j - 1]].append(t)
    spans = {}
    for parent, ts in by.items():
        hi = max(ts)
        j = bisect.bisect_right(mps, hi)
        nxt = mps[j] if j < len(mps) else hi + 0x40
        size = nxt - parent
        if size > 0:
            spans[parent] = size
    return spans


def write_config(spans, outdir):
    base = read(BASE_CONFIG)
    base = re.sub(r'out_directory_path\s*=\s*"[^"]*"',
                  'out_directory_path = "%s"' % outdir.replace("\\", "/"), base)
    block = ["\n\n# ---- generated by fix_stubs_iter.py: explicit spans for",
             "# functions whose exit block was orphaned outside the body.",
             "# size = next mapping entry - this start, rederived each round."]
    for p in sorted(spans):
        block.append("\n[[main.functions]]\naddress = 0x%08X\nsize = 0x%X"
                     % (p, spans[p]))
    with open(WORK_CONFIG, "w", encoding="utf8", newline="\n") as f:
        f.write(base + "\n".join(block) + "\n")


def run_tool():
    if os.path.isdir(OUTDIR):
        shutil.rmtree(OUTDIR)
    os.makedirs(OUTDIR)
    # Config must be a bare filename resolved from the repo root.
    r = subprocess.run([TOOL, os.path.basename(WORK_CONFIG), HEADER],
                       cwd=ROOT, capture_output=True, text=True)
    return r.returncode, (r.stdout or "") + (r.stderr or "")


def main():
    spans = {}
    prev_total = None
    for rnd in range(1, MAX_ROUNDS + 1):
        src = OUTDIR if os.path.isdir(OUTDIR) else os.path.join(ROOT, "generated", "ppc_xenon")
        mps = mapping_addrs(src)
        c = census(src)
        total, distinct = sum(c.values()), len(c)
        print("round %d: census of %s -> %d stub sites, %d distinct targets"
              % (rnd, os.path.basename(src), total, distinct), flush=True)
        if total == 0:
            print("CLEAN: zero stubs.", flush=True)
            break
        if prev_total is not None and total >= prev_total:
            print("STALLED: %d -> %d, no improvement. Stopping." % (prev_total, total),
                  flush=True)
            break
        prev_total = total
        new = derive_spans(c.keys(), mps)
        added = {k: v for k, v in new.items() if k not in spans}
        print("  derived %d spans (%d new), total %d"
              % (len(new), len(added), len(spans) + len(added)), flush=True)
        if not added:
            print("STALLED: no new spans to add. Stopping.", flush=True)
            break
        spans.update(added)
        write_config(spans, OUTDIR)
        rc, log = run_tool()
        tus = len([n for n in os.listdir(OUTDIR)
                   if n.startswith("ppc_recomp.") and n.endswith(".cpp")])
        print("  tool exit=%d, TUs=%d" % (rc, tus), flush=True)
        if rc != 0:
            print("TOOL FAILED:\n" + log[-1500:], flush=True)
            break
    print("final spans applied: %d" % len(spans), flush=True)


if __name__ == "__main__":
    sys.exit(main())
